---
hero_image: images / getting-slag-met-framboos-pi.png
theme: rood
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Aan de slag met de Raspberry Pi
description: Stel je Raspberry Pi op en ontdek wat hij kan doen
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: framboos-pi
site_areas: projecten
hardware: framboos-pi
software: ''
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Invoering
  - 
    title: Wat je nodig zult hebben
  - 
    title: Maak kennis met de Raspberry Pi
  - 
    title: 'Uitdaging: leg de Raspberry Pi uit'
  - 
    title: Verbind je Raspberry Pi
  - 
    title: Een rondleiding door de Raspberry Pi
  - 
    title: Surfen op het web
  - 
    title: 'Uitdaging: verken de Raspberry Pi'
