hero_image: images/banner.png
theme: red
duration: 1
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Getting Started with the Raspberry Pi
description: Set up the Raspberry Pi and explore what it can do.
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: ''
site_areas: codeclub, raspberry-pi
steps:
- title: 'Introduction'
- title: 'Meet the Raspberry Pi '
- title: 'Challenge: Explain the Pi to a Friend'
- title: Connect Your Pi
- title: A Tour of the Pi
- title: Browsing the Web (Optional)
- title: 'Challenge: Explore the Pi'

