hero_image: images/getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: creator, design-0, programming-0, phys-comp-0, manufacture-0, community-0
title: Getting started with the Raspberry Pi
description: Set up your Raspberry Pi and explore what it can do
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: ''
site_areas: codeclub, raspberry-pi
steps:
- title: Introduction
- title: What you will need
- title: Meet the Raspberry Pi
- title: 'Challenge: Explain the Raspberry Pi'
- title: Connect your Raspberry Pi
- title: A tour of the Raspberry Pi
- title: Browsing the web
- title: 'Challenge: explore the Raspberry Pi'
