---
hero_image: Изображения / получение стартер-с-малиново-pi.png
theme: красный
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, production-0, community-0
title: Начало работы с малиной Pi
description: Настройте свой малиновый Pi и исследуйте, что он может сделать
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: Raspberry Pi
site_areas: проектов
hardware: Raspberry Pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Введение
  - 
    title: Что тебе понадобится
  - 
    title: Познакомьтесь с малиной Pi
  - 
    title: 'Задача: объяснить Малину Пи'
  - 
    title: Подключите малину Pi
  - 
    title: Экскурсия по малине Pi
  - 
    title: Просмотр веб-страниц
  - 
    title: 'Задача: исследовать малину Пи'
