---
hero_image: छवियों / आरंभ करने संबंधी-साथ-रास्पबेरी-pi.png
theme: लाल
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, डिजाइन -0, प्रोग्रामिंग -0, भौतिक-कंप -1, निर्माण -0, समुदाय -0
title: रास्पबेरी पीआई के साथ शुरू करना
description: अपनी रास्पबेरी पीआई सेट करें और पता लगाएं कि यह क्या कर सकता है
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: रास्पबेरी पाई
site_areas: परियोजनाओं
hardware: रास्पबेरी पाई
software: ''
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: परिचय
  - 
    title: तुम क्या आवश्यकता होगी
  - 
    title: रास्पबेरी पाई से मिलें
  - 
    title: 'चुनौती: रास्पबेरी पीआई की व्याख्या करें'
  - 
    title: अपने रास्पबेरी पीआई कनेक्ट करें
  - 
    title: रास्पबेरी पाई का दौरा
  - 
    title: वेब ब्राउज़ करना
  - 
    title: 'चुनौती: रास्पबेरी पीआई का पता लगाएं'
