---
hero_image: images/getting-started-with-raspberry-pi.png
theme: đỏ
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Bắt đầu với Raspberry Pi
description: Thiết lập Raspberry Pi của bạn và khám phá những gì nó có thể làm
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: dự án
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Làm quen với Raspberry Pi
  - 
    title: Kết nối Raspberry Pi của bạn
  - 
    title: Hoàn tất thiết lập
  - 
    title: Một vòng khám phá Raspberry Pi
  - 
    title: Duyệt web
  - 
    title: 'Thử thách: khám phá Raspberry Pi'
