---
hero_image: images / getting-started-with-raspberry-pi.png
theme: đỏ
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, thiết kế-0, lập trình-0, phys-comp-1, sản xuất-0, cộng đồng-0
title: Bắt đầu với Raspberry Pi
description: Thiết lập Raspberry Pi của bạn và khám phá những gì nó có thể làm
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: quả mâm xôi
site_areas: dự án
hardware: quả mâm xôi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Giới thiệu
  - 
    title: Những gì bạn sẽ cần
  - 
    title: Gặp gỡ Raspberry Pi
  - 
    title: 'Thách thức: giải thích Raspberry Pi'
  - 
    title: Kết nối Raspberry Pi của bạn
  - 
    title: Một tour du lịch của Raspberry Pi
  - 
    title: Duyệt web
  - 
    title: 'Thách thức: khám phá Raspberry Pi'
