---
hero_image: images / getting-started-com-framboesa-pi.png
theme: vermelho
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programação-0, phys-comp-1, fabricação-0, comunidade-0
title: Começando com o Raspberry Pi
description: Configure o seu Raspberry Pi e explore o que ele pode fazer
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: Raspberry Pi
site_areas: projetos
hardware: Raspberry Pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você vai precisar
  - 
    title: Conheça o Raspberry Pi
  - 
    title: Liga o teu Raspberry Pi
  - 
    title: Termina a instalação
  - 
    title: Um passeio pelo Raspberry Pi
  - 
    title: Navegando pela web
  - 
    title: 'Desafio: explore o Raspberry Pi'
