---
hero_image: slike / početak korištenja-s-malina-pi.png
theme: Crvena
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, dizajn-0, programiranje-0, fiz-comp-1, proizvodnja-0, zajednica-0
title: Početak korištenja Raspberry Pi
description: Postavite Raspberry Pi i istražite što ona može učiniti
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: malina-pi
site_areas: projekti
hardware: malina-pi
software: ''
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Uvod
  - 
    title: Ono što će vam trebati
  - 
    title: Upoznajte rasplodni Pi
  - 
    title: 'Izazov: objasnite Malu Malu'
  - 
    title: Povežite svoj Raspberry Pi
  - 
    title: Razgled Maline Malte
  - 
    title: Pregledavanje weba
  - 
    title: 'Izazov: istražite maline Pi'
