---
hero_image: images/getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Uvod u Raspberry Pi
description: Instalirajte Raspberry Pi i istražite njegove mogućnosti
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 3
last_tested: 2017/01/01
steps:
  - 
    title: Uvod
  - 
    title: Ono što će vam trebati
  - 
    title: Upoznajte rasplodni Pi
  - 
    title: 'Izazov: objasnite Malu Malu'
  - 
    title: Povežite svoj Raspberry Pi
  - 
    title: Razgled Maline Malte
  - 
    title: Pregledavanje weba
  - 
    title: 'Izazov: istražite maline Pi'
