---
hero_image: Kuvien / saada käyntiin-with-vadelma-pi.png
theme: punainen
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, ohjelmointi-0, phys-comp-1, valmistus-0, yhteisö-0
title: Aloittaminen Raspberry Piin kanssa
description: Aseta vadelmasi Pi ja tutki, mitä se voi tehdä
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: vadelma-pi
site_areas: hankkeet
hardware: vadelma-pi
software: ''
version: 4.1.0
last_tested: 01.1.2017
steps:
  - 
    title: esittely
  - 
    title: Mitä tarvitset
  - 
    title: Tapaa Raspberry Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Kiertue Raspberry Pi
  - 
    title: Verkon selaaminen
  - 
    title: 'Haaste: Tutustu Vadelma Pi'
