---
hero_image: images / getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Comenzando con la Raspberry Pi
description: Configura tu Raspberry Pi y explora lo que puede hacer
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducción
  - 
    title: Lo que necesitarás
  - 
    title: Conoce a la Raspberry Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Un recorrido por la Raspberry Pi
  - 
    title: Navegando por la web
  - 
    title: 'Desafío: explorar la Raspberry Pi'
