---
hero_image: delweddau / get-started-with-rasberry-pi.png
theme: Coch
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, dylunio-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Dechrau'r Mws Mws
description: Gosodwch eich Mws Mws ac edrych ar yr hyn y gall ei wneud
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: mafon-pi
site_areas: prosiectau
hardware: mafon-pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Beth fydd ei angen arnoch chi
  - 
    title: Cwrdd â'r Pi Mws
  - 
    title: 'Her: eglurwch y Mws Mws'
  - 
    title: Cysylltwch eich Pi Mws
  - 
    title: Taith o amgylch y Mws Mws
  - 
    title: Yn pori'r we
  - 
    title: 'Her: archwiliwch y Mws Mws'
