---
hero_image: images/getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Mynd i'r afael â'r Raspberry Pi
description: Gosod dy Raspberry Pi a darganfod beth mae'n gallu ei wneud
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Cyflwyniad
  - 
    title: Beth fydd ei angen arnat ti
  - 
    title: Dyma'r Raspberry Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Esboniad o'r Raspberry Pi
  - 
    title: Pori'r We
  - 
    title: 'Her: dod yn gyfarwydd â''r Raspberry Pi'
