---
hero_image: Bilder / Erste Schritte-mit-Himbeer-Pi.png
theme: rot
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, Design-0, Programmierung-0, Phys-Comp-1, Herstellung-0, Community-0
title: Erste Schritte mit dem Raspberry Pi
description: Richte deinen Raspberry Pi ein und erkunde, was er kann
original_url: https://codeclubprojects.org/de-DE/raspberry-pi/getting-started
interests: ''
technologies: Himbeer-Pi
site_areas: Projekte
hardware: Himbeer-Pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Einführung
  - 
    title: Was wirst du brauchen
  - 
    title: Treffen Sie den Raspberry Pi
  - 
    title: 'Herausforderung: Erklären Sie den Raspberry Pi'
  - 
    title: Verbinde deinen Raspberry Pi
  - 
    title: Eine Tour durch den Raspberry Pi
  - 
    title: Im Internet surfen
  - 
    title: 'Herausforderung: Erkunden Sie den Raspberry Pi'
