---
hero_image: images/getting-started-with-raspberry-pi.png
theme: roșu
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Noțiuni de bază ale Raspberry Pi
description: Înființați Raspberry Pi și explorați ce poate face
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: zmeura-pi
site_areas: proiecte
hardware: zmeura-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Ce vei avea nevoie
  - 
    title: Faceți cunoștință cu Zmeura Pi
  - 
    title: Conecteaza Raspberry Pi
  - 
    title: Finalizează configurarea
  - 
    title: Un tur al Zmei Pi
  - 
    title: Navigarea pe web
  - 
    title: 'Provocare: explorați zmeura Pi'
