---
hero_image: images / obtinerea-a început-cu-zmeura-pi.png
theme: roșu
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programare-0, fiz-comp-1, fabricare-0, comunitate-0
title: Noțiuni de bază cu Zmeura Pi
description: Înființați Raspberry Pi și explorați ce poate face
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: zmeura-pi
site_areas: proiecte
hardware: zmeura-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introducere
  - 
    title: Ce vei avea nevoie
  - 
    title: Faceți cunoștință cu Zmeura Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Un tur al Zmei Pi
  - 
    title: Navigarea pe web
  - 
    title: 'Provocare: explorați zmeura Pi'
