---
hero_image: images/getting-started-with-raspberry-pi.png
theme: vermelho
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Começando com o Raspberry Pi
description: Configure o seu Raspberry Pi e explore o que ele pode fazer
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: Projetos
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Introdução
  - 
    title: O que você precisará
  - 
    title: Conheça o Raspberry Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Um passeio pelo Raspberry Pi
  - 
    title: Navegando pela web
  - 
    title: 'Desafio: explique o Raspberry Pi'
