---
hero_image: images / getting-started-with-raspberry-pi.png
theme: merah
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, desain-0, pemrograman-0, phys-comp-1, manufacture-0, community-0
title: Memulai dengan Raspberry Pi
description: Siapkan Raspberry Pi Anda dan jelajahi apa yang bisa dilakukan
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: proyek
hardware: raspberry-pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: pengantar
  - 
    title: Apa yang Anda butuhkan
  - 
    title: Temui Raspberry Pi
  - 
    title: 'Tantangan: jelaskan Raspberry Pi'
  - 
    title: Hubungkan Raspberry Pi Anda
  - 
    title: Tur Raspberry Pi
  - 
    title: Menjelajahi web
  - 
    title: 'Tantangan: jelajahi Raspberry Pi'
