---
hero_image: slike / Get-started-with-raspberry-pi.png
theme: rdeča
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programiranje-0, fiz-comp-1, izdelava-0, skupnost-0
title: Začetek z Raspberry Pi
description: Nastavite svoj malinček Pi in raziščite, kaj lahko naredi
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: malina-pi
site_areas: projektov
hardware: malina-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Uvod
  - 
    title: Kaj boste potrebovali
  - 
    title: Spoznajte Malinko Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Ogled Raspberry Pi
  - 
    title: Brskanje po spletu
  - 
    title: 'Izziv: preučite Raspberry Pi'
