---
hero_image: תמונות / התחלת- with-raspberry-pi.png
theme: אָדוֹם
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: תחילת העבודה עם פטל פטל
description: הגדרת Pi שלך פספל ולחקור מה זה יכול לעשות
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: פאי פטל
site_areas: פרויקטים
hardware: פאי פטל
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: מבוא
  - 
    title: מה שאתה תצטרך
  - 
    title: פגוש את פטל פטל
  - 
    title: 'האתגר: להסביר את פי פטל'
  - 
    title: לחבר את פי פטל שלך
  - 
    title: סיור של פטל פטל
  - 
    title: גלישה באינטרנט
  - 
    title: 'האתגר: לחקור את פי פטל'
