---
hero_image: images/getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: תחילת העבודה עם הראספברי פאי
description: הגדר את הרספברי פאי וחקור מה הוא יכול לעשות
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: הקדמה
  - 
    title: מה תצטרך
  - 
    title: פגוש את הראספברי פאי
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: גלה את הראספברי פאי שלך
  - 
    title: גלישה באינטרנט
  - 
    title: 'האתגר: לחקור את הראספברי פאי'
