---
hero_image: images / getting-started-with-raspberry-pi.png
theme: 빨간
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, 디자인 -0, 프로그래밍 -0, phys-comp-1, 제조 -0, 커뮤니티 -0
title: Raspberry Pi 시작하기
description: 라즈베리 파이를 설정하고 할 수있는 일을 탐험 해보십시오.
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: 라즈베리 파이
site_areas: 프로젝트들
hardware: 라즈베리 파이
software: ''
version: 0
last_tested: 2017-01-01
steps:
  - 
    title: 소개
  - 
    title: 필요한 것
  - 
    title: 라스베리 파이 만나기
  - 
    title: '과제 : 라스베리 파이를 설명하십시오.'
  - 
    title: 라즈베리 파이 연결
  - 
    title: 라스베리 파이 투어
  - 
    title: 웹 브라우징
  - 
    title: '과제 : 라스베리 파이를 탐험 해보십시오.'
