---
hero_image: images / getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Pierwsze kroki z Raspberry Pi
description: Przygotuj swoje Raspberry Pi i sprawdź, co potrafi
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będziesz potrzebować
  - 
    title: Poznaj Raspberry Pi
  - 
    title: Podłącz swoje Raspberry Pi
  - 
    title: Zakończ konfigurację
  - 
    title: Wycieczka po Raspberry Pi
  - 
    title: Przeglądanie sieci
  - 
    title: 'Wyzwanie: odkryj Raspberry Pi'
