---
hero_image: images / getting-started-with-raspberry-pi.png
theme: czerwony
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programowanie-0, phys-comp-1, production-0, community-0
title: Pierwsze kroki z Raspberry Pi
description: Przygotuj swoje Raspberry Pi i sprawdź, co potrafi
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projektowanie
hardware: raspberry-pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Wprowadzenie
  - 
    title: Co będzie potrzebne
  - 
    title: Poznaj Raspberry Pi
  - 
    title: 'Wyzwanie: wyjaśnij Raspberry Pi'
  - 
    title: Połącz swoje Raspberry Pi
  - 
    title: Wycieczka po Raspberry Pi
  - 
    title: Przeglądanie sieci
  - 
    title: 'Wyzwanie: odkryj Raspberry Pi'
