---
hero_image: images/getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: Začíname s Raspberry Pi
description: Spojazdnite si vaše Raspberry Pi a preskúmajte, čo všetko dokáže
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: projects
hardware: raspberry-pi
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: Úvod
  - 
    title: Čo budete potrebovať
  - 
    title: Zoznámte sa s Raspberry Pi
  - 
    title: Connect your Raspberry Pi
  - 
    title: Finish the setup
  - 
    title: Prehliadka Raspberry Pi
  - 
    title: Prehliadanie webu
  - 
    title: 'Úloha: Preskúmajte Raspberry Pi'
