---
hero_image: images / Začíname s-s-malinovou-pi.png
theme: červená
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, dizajn-0, programovanie-0, phys-comp-1, výroba-0, komunita-0
title: Začíname s Raspberry Pi
description: Nastavte si Raspberry Pi a preskúmajte, čo môže urobiť
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: malinový koláč
site_areas: projekty
hardware: malinový koláč
software: ''
version: 3
last_tested: 01.1.2017
steps:
  - 
    title: úvod
  - 
    title: Čo budete potrebovať
  - 
    title: Zoznámte sa s Raspberry Pi
  - 
    title: 'Výzva: vysvetliť Raspberry Pi'
  - 
    title: Pripojte svoje Raspberry Pi
  - 
    title: Prehliadka Raspberry Pi
  - 
    title: Prehliadanie webu
  - 
    title: 'Výzva: preskúmajte Raspberry Pi'
