---
hero_image: images/getting-started-with-raspberry-pi.png
theme: red
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, design-0, programming-0, phys-comp-1, manufacture-0, community-0
title: ' Raspberry Pi শুরু করা'
description: আপনার  Raspberry Pi সেট-আপ করুন এবং এটি দিয়ে কি কি করা যায় তা দেখুন
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: "raspberry Pi\n"
site_areas: প্রজেক্টসমূহ
hardware: "raspberry Pi\n"
software: ''
version: 4.1.0
last_tested: 2017-01-01
steps:
  - 
    title: ভূমিকা
  - 
    title: যা যা প্রয়োজন
  - 
    title: Raspberry Pi এর সাথে পরিচিত হউন
  - 
    title: Raspberry Pi সংযুক্ত করুন
  - 
    title: সেট-আপ সম্পন্ন করুন
  - 
    title: Raspberry Pi এর সাথে ভ্রমণ
  - 
    title: ওয়েব ব্রাউজিং
  - 
    title: 'Challenge: Raspberry Pi দিয়ে কি কি করা যায় তা এক্সপ্লোর করুন'
