---
hero_image: ইমেজ / পেয়ে-শুরু-সঙ্গে-ফলবিশেষ-pi.png
theme: লাল
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, ডিজাইন -0, প্রোগ্রামিং -0, পদার্থ-কম্প-1, উৎপাদন -0, কমিউনিটি -২0
title: রাস্পবেরি পাই দিয়ে শুরু করা
description: আপনার রাস্পবেরি পিআই সেট আপ করুন এবং এটি করতে পারেন কি এক্সপ্লোর
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: ফলবিশেষ-Pi
site_areas: প্রকল্প
hardware: ফলবিশেষ-Pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: ভূমিকা
  - 
    title: আপনার যা দরকার
  - 
    title: রাস্পবেরি পাই পূরণ করুন
  - 
    title: 'চ্যালেঞ্জ: রাস্পবেরি পাই ব্যাখ্যা করুন'
  - 
    title: আপনার রাস্পবেরি পাই সংযুক্ত করুন
  - 
    title: রাস্পবেরী পাই এর একটি সফর
  - 
    title: ওয়েব ব্রাউজিং
  - 
    title: 'চ্যালেঞ্জ: রাস্পবেরি পাই অনুসন্ধান করুন'
