---
hero_image: εικόνες / get-started-with-raspberry-pi.png
theme: το κόκκινο
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, σχεδιασμός-0, προγραμματισμός-0, phys-comp-1, κατασκευή-0, κοινότητα-0
title: Ξεκινώντας με το Raspberry Pi
description: Ρυθμίστε το Raspberry Pi και εξερευνήστε τι μπορεί να κάνει
original_url: https://codeclubprojects.org/en-GB/raspberry-pi/getting-started
interests: ''
technologies: raspberry-pi
site_areas: έργα
hardware: raspberry-pi
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: Εισαγωγή
  - 
    title: Τι θα χρειαστείτε
  - 
    title: Γνωρίστε το Raspberry Pi
  - 
    title: 'Πρόκληση: εξηγήστε το Raspberry Pi'
  - 
    title: Συνδέστε το Raspberry Pi
  - 
    title: Μια περιήγηση στο Raspberry Pi
  - 
    title: Περιήγηση στον ιστό
  - 
    title: 'Πρόκληση: εξερευνήστε το Raspberry Pi'
