---
hero_image: images / getting-started-avec-framboise-pi.png
theme: rouge
duration: 2
listed: true
ingredient: false
copyedit: true
curriculum: 1, conception-0, programmation-0, phys-comp-1, fabrication-0, communauté-0
title: Premiers pas avec le Raspberry Pi
description: Configurez votre Raspberry Pi et explorez ce qu'il peut faire
original_url: https://codeclubprojects.org/fr-FR/raspberry-pi/getting-started
interests: ''
technologies: tarte aux framboises
site_areas: projets
hardware: tarte aux framboises
software: ''
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: introduction
  - 
    title: Ce dont tu auras besoin
  - 
    title: Rencontrez le Raspberry Pi
  - 
    title: 'Défi: expliquer le Raspberry Pi'
  - 
    title: Connectez votre Raspberry Pi
  - 
    title: Une visite du Raspberry Pi
  - 
    title: Surfer sur le web
  - 
    title: 'Défi: explorez le Raspberry Pi'
